version: '3.4'
networks:
  backend:

services:
  customerdb:
      container_name: customer-db
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=apple@123#
      networks:
        - backend
      ports:
        - 8001:1433 
  coreappwithdocker:
    container_name: customer-api
    image: ${DOCKER_REGISTRY-}coreappwithdocker
    build:
      context: .
      dockerfile: CoreAppWithDocker/Dockerfile
    networks:
        - backend
    ports:
        - 8002:1433
    depends_on:
        - customerdb
    environment:
        - DB_HOST=customer-db
        - DB_NAME=customer
        - DB_PASSWORD=apple@123#